
spring:
  servlet:
    multipart:
      max-file-size: 10MB   
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost/db_springboot?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true   
    hibernate:
      ddl-auto: update      
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #format_sql: true
        #dialect: org.hibernate.dialect.SQLServer2012Dialect
  jmx:
    default-domain: control   
# jmx importante para darle un identificador a jpa y funcionen varias apps en un tomcat    
  thymeleaf:
    cache: false
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf

logging:
  level:
    org:  
      hibernate:
        #SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=BIBLIO_UCSM
#spring.datasource.username=admin
#spring.datasource.password=admin
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.hibernate.ddl-auto = update